import type { Todo } from './todo.types'

// Infrastruktur, Testing, QA & Observability, Compliance & Recht, Accessibility

export const TODOS_OPS: Todo[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // Infrastruktur & Backend
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'infra-01',
    titel: 'Superadmin-Tool: Clients anlegen, bearbeiten, löschen',
    beschreibung: '/superadmin/clients: Org anlegen → Workspace → organization_settings → Owner einladen. Superadmin-Org unlöschbar.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: 'Migration 011/020',
  },
  {
    id: 'infra-02',
    titel: 'Impersonation (Admin-Ebenen & DSGVO)',
    beschreibung: 'Read-only Banner, Countdown, geloggt in impersonation_sessions. 15/30/60 Min, Ticket-Referenz Pflicht.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: 'Migration 021',
  },
  {
    id: 'infra-03',
    titel: 'Bug: check_and_reserve_budget RPC (FOR UPDATE + Aggregat)',
    beschreibung: 'FOR UPDATE mit Aggregat-Funktion ist in PostgreSQL ungültig. Fix: Migration 012.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: 'Migration 012 / 2026-03-07',
  },
  {
    id: 'infra-04',
    titel: 'Bug: workspace_members-Eintrag fehlte für neue Org-Owner',
    beschreibung: 'Nach Onboarding war Owner kein workspace_member. Fix: api/onboarding/complete ergänzt.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: '2026-03-07',
  },
  {
    id: 'infra-05',
    titel: 'Bug: Vercel Build-Crash supabaseUrl is required',
    beschreibung: 'supabase-admin.ts Modul-Ebene-Aufruf → Turbopack-Crash. Fix: Proxy-basierte Lazy-Initialisierung.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: '2026-03-11',
  },
  {
    id: 'infra-06',
    titel: 'Bug: Edge Function workflow_finished-Event',
    beschreibung: 'ai-chat/index.ts behandelt jetzt message_end || workflow_finished. dify_conversation_id korrekt gespeichert.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: '2026-03-09',
  },
  {
    id: 'infra-07',
    titel: 'Thinking Mode: thinking_mode in user_preferences',
    beschreibung: 'thinking_mode BOOLEAN (Mig. 015). Edge Function übergibt es als Input an Dify. Toggle in SessionPanel.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'niedrig',
    referenz: 'Migration 015',
  },
  {
    id: 'infra-08b',
    titel: 'Sentry Error Tracking integriert',
    beschreibung: '@sentry/nextjs: server + client + edge config. withSentryConfig() in next.config.ts.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'infra-08c',
    titel: 'Globales Rate Limiting mit Upstash Redis',
    beschreibung: 'proxy.ts: Sliding Window pro IP. Auth 10/15min, public API 20/1h, Chat 30/1min, API 200/1min.',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'infra-08',
    titel: 'PWA: Progressive Web App',
    beschreibung: 'manifest.json, SVG-Icons, Service Worker (Network-first Navigation, Cache-first Assets, Offline-Fallback).',
    status: 'erledigt',
    kategorie: 'Infrastruktur & Backend',
    prioritaet: 'mittel',
    referenz: 'Roadmap',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Testing
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'test-01',
    titel: 'Playwright E2E: Setup + Login-Tests',
    beschreibung: '5 Tests: Form-Rendering, Validierung, Fehler-Mock, Erfolgs-Mock, Passwort-vergessen-Link.',
    status: 'erledigt',
    kategorie: 'Testing',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'test-02',
    titel: 'Playwright E2E: Toro Chat Widget',
    beschreibung: '4 Tests: Widget sichtbar, Eingabe möglich, Mock-Antwort, Optimistic UI.',
    status: 'erledigt',
    kategorie: 'Testing',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'test-03',
    titel: 'Vitest Coverage: Scope auf src/lib/** + src/app/api/** erweitert',
    beschreibung: 'Thresholds bei 50%. Unit Tests für token-counter.ts (7) und errors.ts (4). 48 Tests gesamt.',
    status: 'erledigt',
    kategorie: 'Testing',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'test-04',
    titel: 'E2E: Authenticated Chat-Flow (Login → Chat → Antwort)',
    beschreibung: 'Benötigt E2E_EMAIL und E2E_PASSWORD in Vercel Secrets.',
    status: 'offen',
    kategorie: 'Testing',
    prioritaet: 'mittel',
    referenz: 'nach Test-Account-Setup',
  },
  {
    id: 'test-05',
    titel: 'Vitest Coverage auf 70% erhöhen',
    beschreibung: '83% Lines, 96% Functions, 70% Branches. Neue Tests: validators (27), logger (8), validateBody (6).',
    status: 'erledigt',
    kategorie: 'Testing',
    prioritaet: 'mittel',
    referenz: 'Roadmap Q2',
  },
  {
    id: 'compliance-01',
    titel: 'Art. 50 KI-VO: Persistente KI-Kennzeichnung auf Assistant-Nachrichten',
    beschreibung: '"KI-generiert · Toro" Label in ChatMessage.tsx + cmsg-ki-label CSS-Klasse.',
    status: 'erledigt',
    kategorie: 'Compliance',
    prioritaet: 'hoch',
    referenz: 'Art. 50 Abs. 1 KI-VO (EU AI Act)',
  },
  {
    id: 'infra-09',
    titel: 'Uptime Monitoring: /api/health Endpunkt + externe Überwachung',
    beschreibung: '/api/health: DB-Ping, App-Version, Timestamp (200 ok / 503 degraded). Externes Monitoring konfigurieren.',
    status: 'teilweise',
    kategorie: 'Infrastruktur',
    prioritaet: 'mittel',
    referenz: 'Audit-Bericht 2026-03-13, Punkt 4',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // QA & Observability
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'qa-00',
    titel: 'QA Infrastruktur Phase 1-4: routing-logger, task-classifier, QA Dashboard',
    beschreibung: '5 Tabellen, 5 API-Routes, Dashboard mit 5 Tabs. 35 Unit-Tests grün.',
    status: 'erledigt',
    kategorie: 'QA & Observability',
    prioritaet: 'hoch',
    referenz: 'Migration 027 / 2026-03-11',
  },
  {
    id: 'qa-00b',
    titel: 'LangSmith Integration (Phase 5a) mit DSGVO-Compliance',
    beschreibung: 'hideInputs/hideOutputs. routeRequest als traceable Span. LangSmith-Panel im Performance-Tab.',
    status: 'erledigt',
    kategorie: 'QA & Observability',
    prioritaet: 'hoch',
    referenz: '2026-03-11',
  },
  {
    id: 'qa-01',
    titel: 'LangSmith: Smoke-Test in Production durchführen',
    beschreibung: '3-5 Nachrichten senden, route_request Spans in smith.langchain.com verifizieren.',
    status: 'offen',
    kategorie: 'QA & Observability',
    prioritaet: 'hoch',
    referenz: 'LangSmith / Phase 5a',
  },
  {
    id: 'qa-02',
    titel: 'Vercel: LangSmith Env-Vars in Production setzen',
    beschreibung: 'LANGSMITH_API_KEY, LANGSMITH_PROJECT, LANGSMITH_TRACING als Vercel Environment Variables.',
    status: 'offen',
    kategorie: 'QA & Observability',
    prioritaet: 'hoch',
    referenz: 'Phase 5a',
  },
  {
    id: 'qa-03',
    titel: 'Bias-Evaluierungen: Erste Runs + Metriken in qa_metrics',
    beschreibung: '5 Prompt-Paare, Qualitäts-Parität >= 95%. Wöchentlich Mo 08:00 UTC + manuell.',
    status: 'erledigt',
    kategorie: 'QA & Observability',
    prioritaet: 'mittel',
    referenz: 'QA Dashboard / Art. 10',
  },
  {
    id: 'qa-04',
    titel: 'Lighthouse-CI: Automatische Runs bei jedem Deployment',
    beschreibung: 'Thresholds: Perf >= 80, A11y >= 90, Best-Practices >= 80, SEO >= 80.',
    status: 'erledigt',
    kategorie: 'QA & Observability',
    prioritaet: 'mittel',
    referenz: 'CI/CD / Performance Tab',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Compliance & Recht
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'comp-00a',
    titel: 'AI Act Acknowledgement im Onboarding (Schritt 4)',
    beschreibung: 'ai_act_acknowledged + ai_act_acknowledged_at in user_preferences. Pflicht-Checkbox.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'Migration 009',
  },
  {
    id: 'comp-00b',
    titel: 'DSGVO: LangSmith hideInputs/hideOutputs',
    beschreibung: 'Kein Chat-Inhalt geht in LangSmith Cloud.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'DSGVO Art. 10 / 2026-03-11',
  },
  {
    id: 'comp-00c',
    titel: 'DSGVO: User-ID in qa_routing_log gehasht',
    beschreibung: 'SHA-256 Hash, nur erste 16 Zeichen gespeichert. Nie Klartext.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'routing-logger.ts',
  },
  {
    id: 'comp-01',
    titel: 'Art. 50 KI-VO: Persistente KI-Kennzeichnung im Chat',
    beschreibung: '"KI-generiert · Toro" Label in ChatMessage.tsx (cmsg-ki-label).',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'Art. 50 Abs. 1 KI-VO',
  },
  {
    id: 'comp-02',
    titel: 'Art. 14: Human Override / Eskalationsmechanismus',
    beschreibung: 'ThumbsDown-Button → POST /api/messages/[id]/flag → flagged in messages (Migration 034).',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'Art. 14 EU AI Act',
  },
  {
    id: 'comp-03',
    titel: 'Art. 12: KI-Logging-Vollständigkeit prüfen',
    beschreibung: 'logRouting() Fire-and-forget in Edge Function ai-chat. User-ID SHA-256 gehasht.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'Art. 12 EU AI Act',
  },
  {
    id: 'comp-04',
    titel: 'Art. 11: Technische Dokumentation vor Launch',
    beschreibung: 'CLAUDE.md vorhanden, formale Doku (Architektur, Modell-Auswahl, Trainings-Daten-Policy) fehlt.',
    status: 'offen',
    kategorie: 'Compliance & Recht',
    prioritaet: 'mittel',
    referenz: 'Art. 11 EU AI Act',
  },
  {
    id: 'comp-05',
    titel: 'Art. 10: Bias-Evaluierungen durchführen und dokumentieren',
    beschreibung: 'qa_metrics Tabelle bereit. Erste Bias-Runs müssen ausgeführt werden.',
    status: 'offen',
    kategorie: 'Compliance & Recht',
    prioritaet: 'mittel',
    referenz: 'Art. 10 EU AI Act',
  },
  {
    id: 'comp-06',
    titel: 'Art. 9: Risikoregister anlegen',
    beschreibung: 'Formales Risikoregister mit identifizierten Risiken, Wahrscheinlichkeit, Maßnahmen.',
    status: 'offen',
    kategorie: 'Compliance & Recht',
    prioritaet: 'mittel',
    referenz: 'Art. 9 EU AI Act',
  },
  {
    id: 'comp-07',
    titel: 'DSGVO: Vollständiges Verarbeitungsverzeichnis (VVT)',
    beschreibung: 'AVV-Vorlage vorhanden. Vollständiges Verzeichnis fehlt noch.',
    status: 'offen',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'DSGVO Art. 30',
  },
  {
    id: 'comp-07b',
    titel: 'Footer erstellen',
    beschreibung: 'AppFooter.tsx: Impressum, Datenschutz, Barrierefreiheit, Schlichtungsstelle-Link.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'BFSG § 14 / EAA',
  },
  {
    id: 'comp-08',
    titel: 'BFSG: Barrierefreiheitserklärung /accessibility erstellen',
    beschreibung: 'WCAG-Konformitätserklärung, bekannte Lücken, Barriere-Kontakt, Schlichtungsstelle.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'hoch',
    referenz: 'BFSG / EAA',
  },
  {
    id: 'comp-09',
    titel: 'BFSG: Feedbackmechanismus für Barrieren im Footer',
    beschreibung: 'accessibility@tropen.de im Footer und auf /accessibility verlinkt.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'mittel',
    referenz: 'BFSG § 14',
  },
  {
    id: 'comp-10',
    titel: 'BFSG: Schlichtungsstelle benennen (Ombudsstelle BMAS)',
    beschreibung: 'schlichtungsstelle-bgg.de im Footer und auf /accessibility verlinkt.',
    status: 'erledigt',
    kategorie: 'Compliance & Recht',
    prioritaet: 'mittel',
    referenz: 'BFSG § 16',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Accessibility (WCAG 2.1 AA)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'a11y-01',
    titel: 'Chat-Nachrichten: aria-live="polite" hinzufügen',
    beschreibung: 'Screenreader müssen neue Chat-Antworten ankündigen.',
    status: 'erledigt',
    kategorie: 'Accessibility (WCAG 2.1 AA)',
    prioritaet: 'hoch',
    referenz: 'WCAG 4.1.3',
  },
  {
    id: 'a11y-02',
    titel: 'Loading-States: aria-busy="true" auf Container setzen',
    beschreibung: 'aria-busy auf workspace, projects, knowledge, admin/* Hauptcontainer.',
    status: 'erledigt',
    kategorie: 'Accessibility (WCAG 2.1 AA)',
    prioritaet: 'mittel',
    referenz: 'WCAG 4.1.3',
  },
  {
    id: 'a11y-03',
    titel: 'Drawer/Modal: Fokus-Trap + Escape + Rückkehr-Fokus',
    beschreibung: 'useFocusTrap Hook. role="dialog" aria-modal="true" auf allen Drawers/Modals.',
    status: 'erledigt',
    kategorie: 'Accessibility (WCAG 2.1 AA)',
    prioritaet: 'hoch',
    referenz: 'WCAG 2.1.2',
  },
  {
    id: 'a11y-04',
    titel: 'prefers-reduced-motion in globals.css ergänzen',
    beschreibung: 'Media Query: animation-duration + transition-duration auf 0.01ms.',
    status: 'erledigt',
    kategorie: 'Accessibility (WCAG 2.1 AA)',
    prioritaet: 'mittel',
    referenz: 'WCAG 2.3.3',
  },
  {
    id: 'a11y-05',
    titel: 'Icon-Buttons: aria-label Vollständigkeitsprüfung',
    beschreibung: 'ChatInput Send, ChatHeaderStrip Search, Drawer Close-Buttons, Bookmark, ThumbsDown.',
    status: 'erledigt',
    kategorie: 'Accessibility (WCAG 2.1 AA)',
    prioritaet: 'mittel',
    referenz: 'WCAG 1.1.1',
  },
  {
    id: 'a11y-06',
    titel: 'Kontrast-Audit: Alle Farbkombinationen prüfen',
    beschreibung: 'Admin-Seiten migriert, Modale + Drawers Kontrast-Fixes. Alle Kombinationen >=4.5:1 AA.',
    status: 'erledigt',
    kategorie: 'Accessibility (WCAG 2.1 AA)',
    prioritaet: 'mittel',
    referenz: 'WCAG 1.4.3',
  },
]
