import type { Todo } from './todo.types'

// Chat & Workspace, Projekte & Wissensbasis, Paket-System, Design-System & UX

export const TODOS_FEATURES: Todo[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // Chat & Workspace
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'chat-01',
    titel: 'Workspace-Redesign: Monolithische page.tsx aufgeteilt',
    beschreibung: '2067 Zeilen → 13 Komponenten (useWorkspaceState, WorkspaceLayout, LeftNav, ChatArea, EmptyState, ChatMessage, ChatInput, ProjectSidebar, ConvItem, Papierkorb, JungleModal, MergeModal, ConditionalNavBar).',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'hoch',
    referenz: '2026-03-07',
  },
  {
    id: 'chat-02',
    titel: 'Kimi-Style 3-Column Layout',
    beschreibung: '240px LeftNav, ChatArea flex-grow, ProjectSidebar. Mobile mit Overlay-Nav. Start Screen (EmptyState).',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'hoch',
    referenz: '2026-03-07',
  },
  {
    id: 'chat-03',
    titel: 'Multi-Select mit iOS-"Bearbeiten"-Pattern',
    beschreibung: 'Bearbeiten/Fertig im CHATS-Header, Aktionsleiste: Zusammenführen >=2, Verschieben >=1, Löschen >=1. Lösch-Bestätigung inline.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: '2026-03-08',
  },
  {
    id: 'chat-04',
    titel: 'Jungle Order: Struktur-Vorschlag + Zusammenführen',
    beschreibung: 'Edge Function jungle-order mit action:structure + action:merge. Läuft jetzt auf Anthropic direkt (claude-haiku-4-5-20251001), Dify vollständig abgelöst.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: '2026-03-07',
  },
  {
    id: 'chat-05',
    titel: 'Prompt-Bibliothek Phase 1: 5 Core-Vorlagen',
    beschreibung: 'prompt-templates.ts mit FieldDef-Discriminated-Union und assemble(). Vollständig clientseitig.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: '2026-03-07',
  },
  {
    id: 'chat-06',
    titel: 'Prompt-Bibliothek Phase 2: TemplateDrawer',
    beschreibung: 'Slide-down Drawer mit Live-Vorschau. EmptyState Pills → Drawer-Integration.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: '2026-03-08',
  },
  {
    id: 'chat-07',
    titel: 'Artefakte & Merkliste',
    beschreibung: 'artifacts + bookmarks Tabellen (Mig. 022). Chat-Header-Strip, Artefakte-Drawer (oben), Code-Block "Als Artefakt speichern", Bookmark-Icon, /workspace Grid-Seite.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'Migration 022',
  },
  {
    id: 'chat-08',
    titel: 'Startseiten-Chat (Toro-Widget)',
    beschreibung: 'Anonym, 5 Nachrichten, localStorage, gpt-4o-mini. Toro kennt Startseiten-Kontext, CTA nach Limit.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'public/chat/route.ts',
  },
  {
    id: 'chat-09',
    titel: 'Bug: Erste Nachricht im Toro-Widget leer (wrapOpenAI)',
    beschreibung: 'wrapOpenAI bricht ersten Streaming-Call. Fix: wrapOpenAI entfernt, openai direkt verwendet.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'hoch',
    referenz: '2026-03-11',
  },
  {
    id: 'chat-10',
    titel: 'Bug: Workspace-Chat leerer Bildschirm bei erster Nachricht',
    beschreibung: 'sendingRef Race Condition + newConversation() setzt setMessages([]) bevor Optimistic Messages gesetzt. Fix: initialMessages-Parameter in newConversation().',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'hoch',
    referenz: '2026-03-11',
  },
  {
    id: 'chat-11',
    titel: 'Agenten-System Phase 1: agents-Tabelle',
    beschreibung: 'agents Tabelle (Mig. 025). Marketing-Paket mit 5 Agenten + Schnellstart-Chips im ChatInput.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'hoch',
    referenz: 'Migration 025/026',
  },
  {
    id: 'chat-12',
    titel: 'Agenten-System Phase 2: Agent-Dropdown im Chat-Input',
    beschreibung: 'Vollständig implementiert: Dropdown in ChatInput, agent_id wird in conversations gespeichert, beim Conversation-Wechsel wiederhergestellt. Edge Function lädt agent system_prompt und übergibt ihn an Anthropic direkt.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'hoch',
    referenz: 'Roadmap — nächster Schritt',
  },
  {
    id: 'chat-13',
    titel: 'Prompt-Bibliothek Phase 3: Eigene Vorlagen + Team-Vorlagen',
    beschreibung: 'TemplateDrawer hat 3 Tabs: Core-Vorlagen (hardcoded), Meine Vorlagen (POST/DELETE/PATCH /api/prompt-templates), Team-Vorlagen (scope=team). Erstellen, Löschen, Teilen vollständig. Pagination-Fix: .data aus Response extrahieren.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'Migration 024',
  },
  {
    id: 'chat-14',
    titel: 'Projekt-Gedächtnis Phase 2: Manuelles Kontext-Textfeld',
    beschreibung: 'UI-Textarea in projects/page.tsx (instructions-Feld) war vorhanden. Edge Function ergänzt: lädt project.instructions via project_id der Conversation und übergibt project_context an Anthropic direkt.',
    status: 'erledigt',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'Roadmap',
  },
  {
    id: 'chat-15',
    titel: 'Projekt-Gedächtnis Phase 3: Automatische Extraktion via Anthropic',
    beschreibung: 'Toro extrahiert Personen, Deadlines, Entscheidungen, offene Fragen aus Chat-Verlauf → projects.memory. Direkt via Anthropic SDK (kein Dify).',
    status: 'geplant',
    kategorie: 'Chat & Workspace',
    prioritaet: 'niedrig',
    referenz: 'Roadmap',
  },
  {
    id: 'chat-16',
    titel: 'Toro Guard: 4-Schichten Moderations-System',
    beschreibung: 'Automatisch → KI-Review (Risk Score 0-100) → Manuell → Community. Status-System. Aggressivitäts-Slider statt alles/nichts.',
    status: 'geplant',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'Roadmap',
  },
  {
    id: 'chat-17',
    titel: 'Real-Time Websuche für Toro',
    beschreibung: 'Toro kann live im Web suchen. V2 Feature.',
    status: 'geplant',
    kategorie: 'Chat & Workspace',
    prioritaet: 'niedrig',
    referenz: 'Roadmap V2',
  },
  {
    id: 'chat-18',
    titel: 'Voice Output',
    beschreibung: 'Text-to-Speech für Toro-Antworten. Noch nicht implementiert — eigene Lösung über Anthropic/OpenAI TTS.',
    status: 'geplant',
    kategorie: 'Chat & Workspace',
    prioritaet: 'niedrig',
    referenz: 'Roadmap V2',
  },
  {
    id: 'chat-19',
    titel: 'Multimodalität & Datei-Upload im Chat',
    beschreibung: 'Bild- und Dokument-Upload direkt im Chat-Eingabefeld.',
    status: 'geplant',
    kategorie: 'Chat & Workspace',
    prioritaet: 'niedrig',
    referenz: 'Roadmap V2',
  },
  {
    id: 'chat-20',
    titel: 'Skills anlegen',
    beschreibung: 'Nutzer können eigene Prompt-/Agent-Skills erstellen, benennen und teilen. Community-Tab in /projects zeigt öffentliche Skills. Bewertungs- und Fork-System.',
    status: 'offen',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'Roadmap',
  },
  {
    id: 'chat-21',
    titel: 'SKILL.md System: Toro-Modellwahl & Zusammenfassungsqualität',
    beschreibung: 'Drei Verbesserungen am SKILL.md/Skills-System: (1) Modellwahl-Optimierung (2) Zusammenfassungs-Qualität (3) Workspace-Erstellung verbessern.',
    status: 'offen',
    kategorie: 'Chat & Workspace',
    prioritaet: 'mittel',
    referenz: 'SKILL.md',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Projekte & Wissensbasis
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'proj-01',
    titel: 'Smarte Projekte Phase 1: /projects Seite',
    beschreibung: '4 Tabs (Meine Projekte, Meine Agenten, Community, Vorlagen). Projekt-Felder: Kontext, Ton, Sprache, Zielgruppe, Gedächtnis.',
    status: 'erledigt',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'hoch',
    referenz: 'Migration 016 / 2026-03-09',
  },
  {
    id: 'proj-02',
    titel: 'Wissensbasis & RAG: Fundament',
    beschreibung: 'pgvector EU, text-embedding-3-small, 3 Ebenen (Org/User/Projekt). Dokument-Upload UI + Edge Functions knowledge-search + knowledge-ingest.',
    status: 'erledigt',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'hoch',
    referenz: 'Migration 017/018',
  },
  {
    id: 'proj-05',
    titel: 'RAG Pipeline: knowledge-search + ai-chat Integration',
    beschreibung: 'knowledge-search Edge Function deployed. ai-chat ruft knowledge-search auf, injiziert Top-5 Chunks als knowledge_context direkt in den Anthropic System-Prompt.',
    status: 'erledigt',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'proj-06',
    titel: 'knowledge-ingest: Edge Function Crash-Ursache finden',
    beschreibung: 'Root Cause (2026-03-18): retryDoc() rief Ingest auf ohne Datei in Storage → "Object not found". Außerdem: bei Storage-Upload-Fehler blieb Dokument in "processing" hängen. Fix: (1) handleFiles bereinigt DB-Record bei Storage-Fehler. (2) retryDoc löscht Dokument automatisch wenn Datei fehlt.',
    status: 'erledigt',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'proj-07',
    titel: 'RAG: knowledge_context in Anthropic System-Prompt',
    beschreibung: 'Erledigt mit Dify-Ablösung: knowledge_context wird direkt in den Anthropic System-Prompt injiziert (ai-chat Edge Function). Kein manueller Schritt mehr nötig.',
    status: 'erledigt',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'proj-03',
    titel: 'Wissensbasis Phase 2: Google Drive, Notion, RSS',
    beschreibung: 'Externe Quellen anbinden: Google Drive Sync, Notion, RSS Feeds, Web-Seiten manuell.',
    status: 'geplant',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'niedrig',
    referenz: 'Roadmap Phase 3',
  },
  {
    id: 'proj-04',
    titel: 'n8n/Make Integration',
    beschreibung: 'Trigger aus Tropen OS, n8n als Agent-Tool, Tropen OS als n8n Node.',
    status: 'geplant',
    kategorie: 'Projekte & Wissensbasis',
    prioritaet: 'niedrig',
    referenz: 'Roadmap',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Paket-System
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'paket-01',
    titel: 'Paket-System Phase 1: Marketing-Paket',
    beschreibung: '5 Agenten. Schnellstart-Chips im ChatInput. Superadmin aktiviert pro Org.',
    status: 'erledigt',
    kategorie: 'Paket-System',
    prioritaet: 'hoch',
    referenz: 'Migration 026 / 2026-03-10',
  },
  {
    id: 'paket-02',
    titel: 'Paket-System Phase 2: Marketing-Paket Vollausbau',
    beschreibung: '10 Agenten, Hootsuite/Buffer/Mailchimp/Canva/HubSpot-Integration.',
    status: 'geplant',
    kategorie: 'Paket-System',
    prioritaet: 'mittel',
    referenz: 'Roadmap',
  },
  {
    id: 'paket-03',
    titel: 'Wissenschafts-Paket',
    beschreibung: '10 Agenten, Zotero-Anbindung, DFG/Horizon-Antragsvorlagen. Risiko: nur mit Partner.',
    status: 'geplant',
    kategorie: 'Paket-System',
    prioritaet: 'niedrig',
    referenz: 'Roadmap',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // Design-System & UX
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'ds-01',
    titel: 'Design-System: Türkis/Teal vollständig entfernt',
    beschreibung: 'Alle teal/cyan Farben durch var(--accent) ersetzt. Gilt global.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'hoch',
    referenz: '2026-03-07/08',
  },
  {
    id: 'ds-02',
    titel: 'Content-Breiten-System',
    beschreibung: '.content-max 1200px, .content-narrow 720px, .content-wide 1400px, .content-full. Alle Seiten migriert.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'mittel',
    referenz: '2026-03-07',
  },
  {
    id: 'ds-03',
    titel: 'Globale Typografie & Utility-Klassen',
    beschreibung: '.t-primary, .t-secondary, .t-dezent, .chip, .chip--active, .dropdown, .dropdown-item in globals.css.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'mittel',
    referenz: '2026-03-08',
  },
  {
    id: 'ds-04',
    titel: 'Kosten-Forecast im SessionPanel',
    beschreibung: 'forecastCost implementiert. Warnungen ab 5/10 EUR. Session-Kosten-Warnung ab 0.10/0.50 EUR.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'mittel',
    referenz: 'Roadmap',
  },
  {
    id: 'ds-06',
    titel: 'Layout-Standard-Bereinigung aller Seiten',
    beschreibung: 'Outer-Wrapper entfernt, content-max direkt als Root. body flex-column + main flex:1.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'hoch',
    referenz: '2026-03-13',
  },
  {
    id: 'ds-07',
    titel: 'Artefakte: Eigene Seite /artifacts + NavBar-Link',
    beschreibung: '/artifacts als eigenständige Seite. NavBar: Archive-Icon + Link für Member.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'mittel',
    referenz: '2026-03-13',
  },
  {
    id: 'ds-08',
    titel: 'Department aus Member-Nav → Admin-Nav verschoben',
    beschreibung: 'Department-Link nur noch in Admin-Nav sichtbar.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'mittel',
    referenz: '2026-03-13',
  },
  {
    id: 'ds-09',
    titel: 'Modelle für Members: Toggle in Admin/Models',
    beschreibung: 'members_see_models Boolean in organization_settings (Mig. 035). Toggle in admin/models Seite.',
    status: 'erledigt',
    kategorie: 'Design-System & UX',
    prioritaet: 'mittel',
    referenz: '2026-03-13',
  },
  {
    id: 'ds-05',
    titel: 'Proaktive Hilfe: UI für proactive_hints',
    beschreibung: 'proactive_hints Boolean in user_preferences (Mig. 023). Settings-UI fehlt noch.',
    status: 'offen',
    kategorie: 'Design-System & UX',
    prioritaet: 'niedrig',
    referenz: 'Migration 023',
  },
]
