// src/lib/audit/checkers/slop-detection-checker.ts
// Cat-26: KI-Code-Hygiene — detects patterns common in unreviewed AI-generated code.
//
// OVERLAP NOTES (checked against existing rules):
//   slop-rule-1: cat-18-rule-6 counts generic TODO/FIXME without ticket.
//                This rule targets AI-template language specifically ("implement", "your logic", etc.)
//   slop-rule-3: cat-2-rule-8 checks for commented-out code blocks.
//                This rule checks comment-to-code RATIO (overcommenting), not commented-out code.
//   slop-rule-4: cat-3-rule-30 (checkHardcodedSecrets) finds real embedded secret values.
//                This rule finds placeholder TEMPLATE text ("YOUR_API_KEY_HERE") — complementary.
//
// Tone: factual, not judgmental. "This file shows patterns common in AI-generated code."

import { readFileSync } from 'fs'
import { join } from 'path'
import type { AuditContext, RuleResult, Finding } from '../types'

function readContent(ctx: AuditContext, relPath: string): string | null {
  if (ctx.fileContents) {
    const c = ctx.fileContents.get(relPath)
    if (c !== undefined) return c
  }
  if (ctx.rootPath) {
    try { return readFileSync(join(ctx.rootPath, relPath), 'utf-8') } catch { return null }
  }
  return null
}

function pass(id: string, score: number, reason: string): RuleResult {
  return { ruleId: id, score, reason, findings: [], automated: true }
}

function fail(id: string, score: number, reason: string, findings: Finding[]): RuleResult {
  return { ruleId: id, score, reason, findings, automated: true }
}

function isSourceFile(path: string): boolean {
  return (path.endsWith('.ts') || path.endsWith('.tsx') || path.endsWith('.js') || path.endsWith('.jsx'))
    && !path.includes('.test.') && !path.includes('.spec.') && !path.includes('.generated.')
    && !path.includes('/migrations/') && !path.includes('/node_modules/')
}

// ── slop-rule-1: Placeholder-Kommentare ─────────────────────────────────────
// Targets AI-generated template language — distinct from generic TODOs (cat-18-rule-6).
// Generic TODOs without tickets are already counted there.
// This rule specifically flags AI-style "not yet implemented" placeholders.

const AI_PLACEHOLDER_PATTERNS = [
  /\/\/\s*TODO:\s*implement\b/i,
  /\/\/\s*add your (logic|code|implementation) here/i,
  /\/\/\s*this is a placeholder/i,
  /\/\/\s*replace with (actual|real|your)/i,
  /\/\/\s*implement (this|the logic|me)\b/i,
  /\/\/\s*TODO:\s*add (actual|real|proper) (logic|implementation|code)/i,
  /\/\/\s*\[?placeholder\]?/i,
  /\/\/\s*insert (your|the actual|logic) here/i,
  /\/\/\s*fill in (the|your) (logic|implementation|code)/i,
]

const HAS_TICKET_REF = /(?:#\d+|[A-Z]+-\d+)/

export async function checkPlaceholderComments(ctx: AuditContext): Promise<RuleResult> {
  const findings: Finding[] = []
  let totalPlaceholders = 0

  for (const file of ctx.repoMap.files) {
    if (!isSourceFile(file.path)) continue
    const content = readContent(ctx, file.path)
    if (!content) continue

    const lines = content.split('\n')
    const filePlaceholders: number[] = []

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      if (HAS_TICKET_REF.test(line)) continue
      for (const pattern of AI_PLACEHOLDER_PATTERNS) {
        if (pattern.test(line)) {
          filePlaceholders.push(i + 1)
          totalPlaceholders++
          break
        }
      }
    }

    if (filePlaceholders.length > 0) {
      findings.push({
        severity: 'medium',
        message: `${filePlaceholders.length} placeholder comment(s) without ticket reference — AI-generated unfinished code`,
        filePath: file.path,
        line: filePlaceholders[0],
        suggestion: "Cursor-Prompt: 'Find all placeholder comments in this file (lines with TODO: implement, Add your logic here, etc.) and either implement them or create GitHub issues with #number references. File: " + file.path + "'",
        agentSource: 'slop',
      })
    }
  }

  if (totalPlaceholders <= 3) {
    return pass('cat-26-rule-1', 5, `${totalPlaceholders === 0 ? 'No' : 'Minimal'} AI-style placeholder comments found`)
  }

  const score = totalPlaceholders > 10 ? 1 : totalPlaceholders > 6 ? 2 : 3
  return fail('cat-26-rule-1', score,
    `${totalPlaceholders} AI-style placeholder comments — indicate unreviewed generated code`,
    findings.slice(0, 8)) // cap findings to avoid noise
}

// ── slop-rule-2: KI-Tool-Fingerprints ───────────────────────────────────────

const AI_FINGERPRINT_PATTERNS = [
  { pattern: /\/\/\s*Generated by (Lovable|Bolt|Cursor|Copilot|GitHub Copilot)/i, label: 'AI-tool attribution comment' },
  { pattern: /\/\/\s*Copilot suggestion/i, label: 'Copilot suggestion comment' },
  { pattern: /\/\*\s*AI-generated\s*\*\//i, label: 'AI-generated block comment' },
  { pattern: /\/\/\s*This file was (auto-?)?generated/i, label: 'Auto-generated file comment' },
]
const AI_FINGERPRINT_FILES = ['.bolt/prompt', '.bolt/ignore']

export async function checkAiToolFingerprints(ctx: AuditContext): Promise<RuleResult> {
  const findings: Finding[] = []

  // Check for .bolt/prompt or similar tool files
  for (const filePath of AI_FINGERPRINT_FILES) {
    const content = readContent(ctx, filePath)
    if (content !== null) {
      findings.push({
        severity: 'info',
        message: `AI tool artifact file found: ${filePath} — documents the original AI-generation prompt`,
        filePath,
        suggestion: "Cursor-Prompt: 'Review " + filePath + " and decide if this prompt artifact should be removed from the repository or documented in a README section'",
        agentSource: 'slop',
      })
    }
  }

  // Check source files for AI attribution comments
  for (const file of ctx.repoMap.files) {
    if (!isSourceFile(file.path)) continue
    const content = readContent(ctx, file.path)
    if (!content) continue

    for (const { pattern, label } of AI_FINGERPRINT_PATTERNS) {
      if (pattern.test(content)) {
        findings.push({
          severity: 'info',
          message: `${label} in ${file.path} — confirm the code has been reviewed`,
          filePath: file.path,
          suggestion: "Cursor-Prompt: 'Review all AI-generated sections in " + file.path + " and remove attribution comments after verification. Ensure logic is correct and not just a template.'",
          agentSource: 'slop',
        })
        break // one finding per file
      }
    }
  }

  if (findings.length === 0) return pass('cat-26-rule-2', 5, 'No AI tool fingerprints found in source files')
  return fail('cat-26-rule-2', 4,
    `${findings.length} AI tool fingerprint(s) found — review to confirm code was validated`,
    findings)
}

// ── slop-rule-3: Überkommentierung (comment-to-code ratio) ───────────────────
// DISTINCT from cat-2-rule-8 (checkCommentedOutCode): that checks commented-out code BLOCKS.
// This rule checks if a file has too many EXPLANATORY comments relative to code lines.
// AI tends to explain every trivial step; experienced devs comment only non-obvious logic.

const COMMENT_LINE = /^\s*(\/\/|\/\*|\*)/
const CODE_LINE = /\S/

export async function checkOvercommenting(ctx: AuditContext): Promise<RuleResult> {
  const findings: Finding[] = []

  for (const file of ctx.repoMap.files) {
    if (!file.path.endsWith('.ts') && !file.path.endsWith('.tsx')) continue
    const content = readContent(ctx, file.path)
    if (!content) continue

    const lines = content.split('\n').filter(l => CODE_LINE.test(l))
    if (lines.length < 50) continue // too small to measure meaningfully

    const commentLines = lines.filter(l => COMMENT_LINE.test(l)).length
    const ratio = commentLines / lines.length

    if (ratio > 0.40) {
      const pct = Math.round(ratio * 100)
      findings.push({
        severity: 'info',
        message: `${file.path} has ${pct}% comment lines — overcommenting is a common AI-generation pattern`,
        filePath: file.path,
        suggestion: "Cursor-Prompt: 'Remove trivial comments that just restate the code in " + file.path + ". Keep only comments that explain non-obvious logic, business rules, or WHY (not what).'",
        agentSource: 'slop',
      })
    }
  }

  if (findings.length === 0) return pass('cat-26-rule-3', 5, 'Comment density looks natural — no overcommenting detected')
  return fail('cat-26-rule-3', findings.length > 4 ? 3 : 4,
    `${findings.length} file(s) with unusually high comment ratio`,
    findings)
}

// ── slop-rule-4: Placeholder-Credentials und Dummy-Werte ────────────────────
// DISTINCT from cat-3-rule-30 (checkHardcodedSecrets): that finds REAL embedded secret values.
// This rule finds TEMPLATE PLACEHOLDER TEXT — unfilled AI-generated stubs.
// Example: "YOUR_API_KEY_HERE" vs "AIzaSy..." (the latter is a real key, caught by secrets check).

const PLACEHOLDER_PATTERNS = [
  /["']YOUR[_\s-](API[_\s-]KEY|TOKEN|SECRET)[_\s-]HERE["']/i,
  /["']INSERT[_\s-]YOUR[_\s-]/i,
  /["']REPLACE[_\s-]WITH[_\s-]/i,
  /["']your-project-id["']/i,
  /["']your[_-]api[_-]key["']/i,
  /["']YOUR_SECRET_HERE["']/i,
  /["']PLACEHOLDER["']/i,
  /=\s*["']?YOUR[_\s]/i,
]

// Files where placeholders are expected and should not be flagged
const PLACEHOLDER_EXEMPT_PATTERNS = [
  '.env.example', '.env.sample', '.env.template',
  'README', 'readme', '.md', '.mdx',
  '.test.', '.spec.', 'example', 'sample', 'template',
  '__mocks__', '/docs/', '/public/',
]

function isPlaceholderExempt(filePath: string): boolean {
  return PLACEHOLDER_EXEMPT_PATTERNS.some(p => filePath.includes(p))
}

export async function checkPlaceholderCredentials(ctx: AuditContext): Promise<RuleResult> {
  const findings: Finding[] = []

  for (const file of ctx.repoMap.files) {
    if (!isSourceFile(file.path)) continue
    if (isPlaceholderExempt(file.path)) continue
    const content = readContent(ctx, file.path)
    if (!content) continue

    const lines = content.split('\n')
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      for (const pattern of PLACEHOLDER_PATTERNS) {
        if (pattern.test(line)) {
          // Determine severity: higher for src/ files, medium for config
          const isConfigFile = file.path.includes('config') || file.path.endsWith('.json') || file.path.endsWith('.yaml')
          findings.push({
            severity: isConfigFile ? 'medium' : 'high',
            message: `Placeholder value in ${file.path}:${i + 1} — unfilled AI-generated template`,
            filePath: file.path,
            line: i + 1,
            suggestion: "Cursor-Prompt: 'Find all placeholder values (YOUR_API_KEY_HERE, INSERT_YOUR_*, REPLACE_WITH_*) in " + file.path + " and move them to environment variables. Update .env.example with the variable name.'",
            agentSource: 'slop',
          })
          break
        }
      }
    }
  }

  if (findings.length === 0) return pass('cat-26-rule-4', 5, 'No unfilled placeholder values found in source files')

  const hasHighSeverity = findings.some(f => f.severity === 'high')
  return fail('cat-26-rule-4', hasHighSeverity ? 0 : 2,
    `${findings.length} placeholder template value(s) — could cause production failures`,
    findings)
}

// ── slop-rule-5: Inkonsistente Kommentar-Sprache ─────────────────────────────
// AI changes comment language based on prompt language — projects often show mixed EN/DE.

// Simple heuristic word lists for language detection in comments
const GERMAN_COMMENT_MARKERS = [
  /\b(erstellt|prüft|gibt|gibt zurück|berechnet|holt|sendet|setzt|löscht|aktualisiert|initialisiert)\b/i,
  /\b(diese|dieses|dieser|hier|konfiguration|zustand|anfrage|antwort|wenn|dann|sonst)\b/i,
  /\b(fehler|erfolg|prüfe|hole|sende|erstelle|lösche|aktualisiere)\b/i,
]

const ENGLISH_COMMENT_MARKERS = [
  /\b(creates|checks|returns|calculates|fetches|sends|sets|deletes|updates|initializes)\b/i,
  /\b(this|these|here|configuration|state|request|response|if|then|else)\b/i,
  /\b(error|success|check|fetch|send|create|delete|update)\b/i,
]

function detectLanguage(line: string): 'de' | 'en' | 'unknown' {
  let deScore = 0
  let enScore = 0
  for (const p of GERMAN_COMMENT_MARKERS) { if (p.test(line)) deScore++ }
  for (const p of ENGLISH_COMMENT_MARKERS) { if (p.test(line)) enScore++ }
  if (deScore > enScore) return 'de'
  if (enScore > deScore) return 'en'
  return 'unknown'
}

const COMMENT_LINE_EXTRACT = /^\s*\/\/(.+)$/

export async function checkMixedCommentLanguage(ctx: AuditContext): Promise<RuleResult> {
  const findings: Finding[] = []

  for (const file of ctx.repoMap.files) {
    if (!file.path.endsWith('.ts') && !file.path.endsWith('.tsx')) continue
    const content = readContent(ctx, file.path)
    if (!content) continue

    const lines = content.split('\n')
    let deCount = 0
    let enCount = 0

    for (const line of lines) {
      const match = COMMENT_LINE_EXTRACT.exec(line)
      if (!match) continue
      const commentText = match[1]
      const lang = detectLanguage(commentText)
      if (lang === 'de') deCount++
      else if (lang === 'en') enCount++
    }

    const totalDetected = deCount + enCount
    if (totalDetected < 5) continue // not enough data

    const minorLang = Math.min(deCount, enCount)
    const minorRatio = minorLang / totalDetected

    if (minorRatio > 0.20) {
      const dominant = deCount > enCount ? 'Deutsch' : 'Englisch'
      const minority = deCount > enCount ? 'English' : 'Deutsch'
      findings.push({
        severity: 'info',
        message: `${file.path}: comments mix ${dominant} (${Math.round((1 - minorRatio) * 100)}%) and ${minority} (${Math.round(minorRatio * 100)}%) — typical of multi-session AI generation`,
        filePath: file.path,
        suggestion: `Cursor-Prompt: 'Standardize all comments in ${file.path} to ${dominant}. Translate the ${minority} comments to match the dominant language.'`,
        agentSource: 'slop',
      })
    }
  }

  if (findings.length === 0) return pass('cat-26-rule-5', 5, 'Comment language is consistent across source files')
  return fail('cat-26-rule-5', findings.length > 3 ? 3 : 4,
    `${findings.length} file(s) with mixed comment language`,
    findings)
}
