export interface LpContent {
  nav: {
    links: { label: string; href: string }[]
    cta: string
  }
  hero: {
    eyebrow: string
    h1: [string, string, string]
    sub: string
    ctaPrimary: string
    ctaSecondary: string
  }
  stats: { value: string; text: string }[]
  features: {
    tag: string
    h2: [string, string]
    items: { n: string; title: string; text: string }[]
  }
  howItWorks: {
    tag: string
    h2: [string, string]
    steps: { n: string; title: string; desc: string; file: string; code: string }[]
  }
  categories: {
    tag: string
    h2: [string, string]
    items: string[]
    badgeRules: string
  }
  compliance: {
    tag: string
    h2: [string, string, string]
    sub: string
    cards: { title: string; text: string }[]
  }
  tools: {
    tag: string
    h2: string
    sub: string
  }
  pricing: {
    tag: string
    h2: [string, string]
    sub: string
    toggle: { monthly: string; yearly: string; discount: string }
    plans: {
      id: string
      n: string
      name: string
      desc: string
      price: string
      unit: string
      features: string[]
      cta: string
    }[]
    footnote: string
  }
  cta: {
    h2: [string, string, string]
    sub: string
    button: string
    note: string
  }
  footer: {
    brand: string
    brandSub: string
    socials: string[]
    cols: { title: string; links: { label: string; href: string }[] }[]
    copy: string
    badge: string
  }
}

const de: LpContent = {
  nav: {
    links: [
      { label: 'Kategorien', href: '#kategorien' },
      { label: 'Pricing', href: '#pricing' },
    ],
    cta: 'Anmelden',
  },
  hero: {
    eyebrow: 'Production Readiness Guide',
    h1: ['Ist deine App', 'ready für', 'echte User?'],
    sub: '60 Sekunden. 25 Kategorien. Ein Score.\nWir prüfen was Cursor, Lovable und Bolt nicht prüfen —\nDSGVO, Security, Barrierefreiheit.',
    ctaPrimary: 'Kostenlos scannen',
    ctaSecondary: 'Demo ansehen',
  },
  stats: [
    { value: '94%', text: 'der Vibe-Apps verstoßen gegen DSGVO' },
    { value: '+23%', text: 'Ø Score-Verbesserung nach erstem Fix' },
    { value: '195', text: 'Regeln in 25 Kategorien' },
    { value: '€20.000', text: 'durchschn. DSGVO-Bußgeld' },
  ],
  features: {
    tag: 'Was wir finden',
    h2: ['Die Probleme die dein', 'Coding-Tool übersieht.'],
    items: [
      { n: '01', title: 'DSGVO & Legal', text: 'Impressum fehlt, Cookies ohne Consent, personenbezogene Daten falsch gespeichert. Das sind keine Kleinigkeiten — das sind Bußgelder.' },
      { n: '02', title: 'Security & Auth', text: 'API-Routes ohne Validierung, Secrets im Code, fehlende Rate-Limits. Ein schlechter Tag kann deine gesamte User-Datenbank leaken.' },
      { n: '03', title: 'Barrierefreiheit', text: 'Fehlende Alt-Texte, kein Keyboard-Support, Kontraste unter dem Minimum. Seit Juni 2025 ist Barrierefreiheit in der EU Pflicht (BFSG).' },
      { n: '04', title: 'Code-Qualität & Architektur', text: 'Dateien über 500 Zeilen, Business-Logik in UI-Komponenten, keine Error-Boundaries. Code der funktioniert ist nicht Code der wartbar ist.' },
    ],
  },
  howItWorks: {
    tag: "So funktioniert's",
    h2: ['Drei Schritte.', 'Kein Setup.'],
    steps: [
      { n: 'I', title: 'Projekt verbinden', desc: 'Ordner auswählen — dein Code bleibt lokal. Wir speichern nichts. GitHub-Connect kommt bald.', file: '.cursorrules', code: `# Quality Rules — Generated by Tropen OS\n\n## Security\n- Validate all inputs with Zod\n- Auth check as first line in every API route\n- Never return error.message to client` },
      { n: 'II', title: 'Scan in 60 Sekunden', desc: '25 Kategorien. 195 Regeln. Optional: 4 KI-Modelle prüfen unabhängig im Deep Review.', file: 'audit-result.json', code: `{\n  "score": 71,\n  "status": "risky",\n  "findings": 24,\n  "critical": 3,\n  "categories": {\n    "security": 40,\n    "dsgvo": 55\n  }\n}` },
      { n: 'III', title: 'Aufgaben für deine KI', desc: 'Jedes Finding wird zum kopierbaren Prompt. Du musst DSGVO nicht verstehen — deine KI fixt es.', file: 'finding-prompt.txt', code: `Problem: Missing rate limiting on /api/auth\n\nFile: src/app/api/auth/route.ts\n\nWhat to do:\nAdd Upstash rate limiting.\nMax 5 requests/minute per IP.\nReturn 429 with Retry-After header.` },
    ],
  },
  categories: {
    tag: 'Vollständige Abdeckung',
    h2: ['25 Kategorien.', 'Kein Punkt wird übersprungen.'],
    items: ['Security', 'DSGVO', 'BFSG', 'AI Act', 'Code-Qualität', 'Architektur', 'Performance', 'Testing', 'API-Design', 'Datenbank', 'Observability', 'CI/CD', 'Dependencies', 'Error Handling', 'State Management', 'Design System', 'Accessibility', 'Git Governance', 'Cost Awareness', 'Dokumentation', 'Infrastructure', 'Supply Chain', 'Namenskonventionen', 'Skalierbarkeit', 'PWA'],
    badgeRules: '26 Build-Time-Regeln',
  },
  compliance: {
    tag: 'EU-Compliance',
    h2: ['Compliance ist', 'Schutz, nicht', 'Bürokratie.'],
    sub: 'Europäische Regulierung schützt echte Menschen. Wir übersetzen sie in konkrete Code-Checks.',
    cards: [
      { title: 'DSGVO', text: 'Datenschutzerklärung, Consent, Datenexport, Löschrecht — auf Code-Architektur-Ebene geprüft.' },
      { title: 'BFSG', text: 'Seit Juni 2025 Pflicht für B2C-Apps in der EU. Barrierefreiheit ist kein Nice-to-have mehr.' },
      { title: 'AI Act', text: 'Transparenzpflicht, Risiko-Klassifizierung. Das erste Tool das AI Act auf Code-Ebene prüft.' },
    ],
  },
  tools: {
    tag: 'Egal womit du gebaut hast',
    h2: 'Funktioniert mit jedem Stack.',
    sub: 'Kein Lock-in. Kein Framework-Zwang.',
  },
  pricing: {
    tag: 'Pricing',
    h2: ['Einfache Preise.', 'Keine Überraschungen.'],
    sub: 'Start free und scale wenn du bereit bist.',
    toggle: { monthly: 'Monatlich', yearly: 'Jährlich', discount: '−17%' },
    plans: [
      {
        id: 'free', n: '01', name: 'Free', desc: 'Für Hobby-Projekte',
        price: '€0', unit: '/Monat',
        features: ['1 Projekt', '10 Scans / Monat', 'Top 5 Findings', 'Score-Tracking', '.cursorrules Export'],
        cta: 'Kostenlos starten',
      },
      {
        id: 'pro', n: '02', name: 'Pro', desc: 'Für Gründer die launchen wollen',
        price: '€39', unit: '/Monat',
        features: ['3 Projekte', 'Unbegrenzte Scans', 'Deep Review (4 KI-Modelle)', 'EU-Compliance (DSGVO, BFSG, AI Act)', 'Prompt-Export', 'Aufgabenliste', 'Score-Verlauf'],
        cta: '14 Tage kostenlos',
      },
      {
        id: 'agency', n: '03', name: 'Agency', desc: 'Für Teams und Freelancer',
        price: '€199', unit: '/Monat',
        features: ['Unlimitierte Projekte', 'API-Zugang', 'Compliance-Reports', 'Priority Support', 'Team-Verwaltung'],
        cta: 'Kontakt aufnehmen',
      },
    ],
    footnote: 'Alle Pläne inklusive .cursorrules Export, HTTPS und automatische Updates.',
  },
  cta: {
    h2: ['Scan dein Projekt.', 'Bevor es jemand', 'anderes tut.'],
    sub: '60 Sekunden. Kostenlos. Keine Kreditkarte.',
    button: 'Jetzt kostenlos scannen',
    note: 'Keine Kreditkarte erforderlich',
  },
  footer: {
    brand: 'Tropen OS',
    brandSub: 'Production Readiness Guide für Vibe-Coders. Gebaut in Brandenburg. EU-Server.',
    socials: ['GitHub', 'Twitter'],
    cols: [
      { title: 'Produkt', links: [{ label: 'Features', href: '#features' }, { label: 'Pricing', href: '#pricing' }, { label: 'Kategorien', href: '#kategorien' }] },
      { title: 'Entwickler', links: [{ label: '.cursorrules', href: '#' }, { label: 'Dokumentation', href: '#' }] },
      { title: 'Rechtliches', links: [{ label: 'Impressum', href: '/impressum' }, { label: 'Datenschutz', href: '/datenschutz' }, { label: 'Barrierefreiheit', href: '/barrierefreiheit' }] },
    ],
    copy: '© 2026 Tropen OS. All rights reserved.',
    badge: 'EU-Server · DSGVO-konform',
  },
}

const en: LpContent = {
  nav: {
    links: [
      { label: 'Categories', href: '#kategorien' },
      { label: 'Pricing', href: '#pricing' },
    ],
    cta: 'Sign in',
  },
  hero: {
    eyebrow: 'Production Readiness Guide',
    h1: ['Is your app', 'ready for', 'real users?'],
    sub: '60 seconds. 25 categories. One score.\nWe check what Cursor, Lovable and Bolt miss —\nGDPR, security, accessibility.',
    ctaPrimary: 'Scan for free',
    ctaSecondary: 'Watch demo',
  },
  stats: [
    { value: '94%', text: 'of vibe-coded apps violate GDPR' },
    { value: '+23%', text: 'avg. score improvement after first fix' },
    { value: '195', text: 'rules across 25 categories' },
    { value: '€20,000', text: 'avg. GDPR fine' },
  ],
  features: {
    tag: 'What we find',
    h2: ['The problems your', 'coding tool misses.'],
    items: [
      { n: '01', title: 'GDPR & Legal', text: 'Missing imprint, cookies without consent, personal data stored incorrectly. These are not minor issues — they are fines.' },
      { n: '02', title: 'Security & Auth', text: 'API routes without validation, secrets in code, missing rate limits. One bad day can leak your entire user database.' },
      { n: '03', title: 'Accessibility', text: 'Missing alt texts, no keyboard support, contrast below the minimum. Since June 2025, accessibility is mandatory in the EU (BFSG).' },
      { n: '04', title: 'Code Quality & Architecture', text: 'Files over 500 lines, business logic in UI components, no error boundaries. Code that works is not code that is maintainable.' },
    ],
  },
  howItWorks: {
    tag: 'How it works',
    h2: ['Three steps.', 'No setup.'],
    steps: [
      { n: 'I', title: 'Connect project', desc: 'Select a folder — your code stays local. We store nothing. GitHub connect coming soon.', file: '.cursorrules', code: `# Quality Rules — Generated by Tropen OS\n\n## Security\n- Validate all inputs with Zod\n- Auth check as first line in every API route\n- Never return error.message to client` },
      { n: 'II', title: 'Scan in 60 seconds', desc: '25 categories. 195 rules. Optional: 4 AI models review independently in deep review.', file: 'audit-result.json', code: `{\n  "score": 71,\n  "status": "risky",\n  "findings": 24,\n  "critical": 3,\n  "categories": {\n    "security": 40,\n    "gdpr": 55\n  }\n}` },
      { n: 'III', title: 'Tasks for your AI', desc: 'Each finding becomes a copyable prompt. You don\'t need to understand GDPR — your AI fixes it.', file: 'finding-prompt.txt', code: `Problem: Missing rate limiting on /api/auth\n\nFile: src/app/api/auth/route.ts\n\nWhat to do:\nAdd Upstash rate limiting.\nMax 5 requests/minute per IP.\nReturn 429 with Retry-After header.` },
    ],
  },
  categories: {
    tag: 'Full coverage',
    h2: ['25 categories.', 'No point is skipped.'],
    items: ['Security', 'GDPR', 'BFSG', 'AI Act', 'Code Quality', 'Architecture', 'Performance', 'Testing', 'API Design', 'Database', 'Observability', 'CI/CD', 'Dependencies', 'Error Handling', 'State Management', 'Design System', 'Accessibility', 'Git Governance', 'Cost Awareness', 'Documentation', 'Infrastructure', 'Supply Chain', 'Naming Conventions', 'Scalability', 'PWA'],
    badgeRules: '26 build-time rules',
  },
  compliance: {
    tag: 'EU Compliance',
    h2: ['Compliance is', 'protection, not', 'bureaucracy.'],
    sub: 'European regulation protects real people. We translate it into concrete code checks.',
    cards: [
      { title: 'GDPR', text: 'Privacy policy, consent, data export, right to deletion — checked at the code architecture level.' },
      { title: 'BFSG', text: 'Mandatory for B2C apps in the EU since June 2025. Accessibility is no longer optional.' },
      { title: 'AI Act', text: 'Transparency requirements, risk classification. The first tool that checks the AI Act at code level.' },
    ],
  },
  tools: {
    tag: 'No matter what you built with',
    h2: 'Works with any stack.',
    sub: 'No lock-in. No framework required.',
  },
  pricing: {
    tag: 'Pricing',
    h2: ['Simple prices.', 'No surprises.'],
    sub: 'Start free and scale when you are ready.',
    toggle: { monthly: 'Monthly', yearly: 'Yearly', discount: '−17%' },
    plans: [
      {
        id: 'free', n: '01', name: 'Free', desc: 'For hobby projects',
        price: '€0', unit: '/month',
        features: ['1 project', '10 scans / month', 'Top 5 findings', 'Score tracking', '.cursorrules export'],
        cta: 'Start for free',
      },
      {
        id: 'pro', n: '02', name: 'Pro', desc: 'For founders who want to launch',
        price: '€39', unit: '/month',
        features: ['3 projects', 'Unlimited scans', 'Deep review (4 AI models)', 'EU compliance (GDPR, BFSG, AI Act)', 'Prompt export', 'Task list', 'Score history'],
        cta: '14 days free',
      },
      {
        id: 'agency', n: '03', name: 'Agency', desc: 'For teams and freelancers',
        price: '€199', unit: '/month',
        features: ['Unlimited projects', 'API access', 'Compliance reports', 'Priority support', 'Team management'],
        cta: 'Get in touch',
      },
    ],
    footnote: 'All plans include .cursorrules export, HTTPS and automatic updates.',
  },
  cta: {
    h2: ['Scan your project.', 'Before someone', 'else does.'],
    sub: '60 seconds. Free. No credit card.',
    button: 'Scan for free now',
    note: 'No credit card required',
  },
  footer: {
    brand: 'Tropen OS',
    brandSub: 'Production Readiness Guide for Vibe-Coders. Built in Brandenburg. EU servers.',
    socials: ['GitHub', 'Twitter'],
    cols: [
      { title: 'Product', links: [{ label: 'Features', href: '#features' }, { label: 'Pricing', href: '#pricing' }, { label: 'Categories', href: '#kategorien' }] },
      { title: 'Developers', links: [{ label: '.cursorrules', href: '#' }, { label: 'Documentation', href: '#' }] },
      { title: 'Legal', links: [{ label: 'Imprint', href: '/impressum' }, { label: 'Privacy', href: '/datenschutz' }, { label: 'Accessibility', href: '/barrierefreiheit' }] },
    ],
    copy: '© 2026 Tropen OS. All rights reserved.',
    badge: 'EU servers · GDPR compliant',
  },
}

export const LP_CONTENT: Record<string, LpContent> = { de, en }
export function getLpContent(locale: string): LpContent {
  return LP_CONTENT[locale] ?? LP_CONTENT.de
}
